[tool.poetry]
name = "houseuk-data"
version = "0.1.0"
description = "this repo is for data teams working on house uk data"
authors = ["kang wang <kangqiwang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
