[tool.poetry]
name = "houseuk-dashboard"
version = "0.1.0"
description = ""
authors = ["kang wang <kangqiwang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
mypy = "^1.9.0"
requests = "^2.31.0"
pandas = "^2.2.2"
numpy = "^1.26.4"
lxml = "^5.2.1"
pyspark = "^3.5.1"
apache-airflow-providers-cncf-kubernetes = "^8.1.1"
sphinx = "^7.3.7"
beautifulsoup4 = "^4.12.3"
python-dateutil = "^2.9.0.post0"
amber-data-utils = "^0.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
python_version="3.9"

ignore_missing_imports = true